#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
  useradd ever -r
  path="var/ever/data"
  (mkdir -p $path && chown ever:ever -R $path) || true
fi
#DEBHELPER#
